/**
 * Headless Medical Imaging Engine Event Schemas & Enum Specifications
 */

export enum EngineEvents {
  // Lifecycle & Initialization Events
  ENGINE_INITIALIZING = 'ENGINE_INITIALIZING',
  CORNERSTONE_INITIALIZED = 'CORNERSTONE_INITIALIZED',
  METADATA_PROVIDER_REGISTERED = 'METADATA_PROVIDER_REGISTERED',
  IMAGE_LOADER_REGISTERED = 'IMAGE_LOADER_REGISTERED',
  VOLUME_LOADER_REGISTERED = 'VOLUME_LOADER_REGISTERED',
  WEB_WORKERS_READY = 'WEB_WORKERS_READY',
  RENDERING_ENGINE_CREATED = 'RENDERING_ENGINE_CREATED',
  ENGINE_READY = 'ENGINE_READY',
  ENGINE_DESTROYING = 'ENGINE_DESTROYING',
  ENGINE_DESTROYED = 'ENGINE_DESTROYED',

  // DICOM Pipeline & Ingestion Events (Phase 3)
  STUDY_LOADING = 'STUDY_LOADING',
  STUDY_LOADED = 'STUDY_LOADED',
  SERIES_LOADING = 'SERIES_LOADING',
  SERIES_LOADED = 'SERIES_LOADED',
  INSTANCE_LOADING = 'INSTANCE_LOADING',
  INSTANCE_LOADED = 'INSTANCE_LOADED',
  DISPLAYSETS_CREATED = 'DISPLAYSETS_CREATED',
  METADATA_NORMALIZED = 'METADATA_NORMALIZED',
  IMAGEIDS_CREATED = 'IMAGEIDS_CREATED',
  STUDY_CACHED = 'STUDY_CACHED',
  DICOM_PIPELINE_READY = 'DICOM_PIPELINE_READY',

  // Native 2D Viewport & Rendering Events (Phase 4)
  VIEWPORT_CREATED = 'VIEWPORT_CREATED',
  VIEWPORT_DESTROYED = 'VIEWPORT_DESTROYED',
  VIEWPORT_RESIZED = 'VIEWPORT_RESIZED',
  VIEWPORT_ACTIVATED = 'VIEWPORT_ACTIVATED',
  VIEWPORT_RENDERED = 'VIEWPORT_RENDERED',
  DISPLAYSET_BOUND = 'DISPLAYSET_BOUND',
  STACK_LOADED = 'STACK_LOADED',
  FIRST_IMAGE_RENDERED = 'FIRST_IMAGE_RENDERED',
  SLICE_CHANGED = 'SLICE_CHANGED',

  // Enterprise Volume Engine Events (Phase 5)
  VOLUME_BUILDING = 'VOLUME_BUILDING',
  VOLUME_CREATED = 'VOLUME_CREATED',
  VOLUME_LOADING = 'VOLUME_LOADING',
  VOLUME_LOADED = 'VOLUME_LOADED',
  VOLUME_CACHED = 'VOLUME_CACHED',
  VOLUME_EVICTED = 'VOLUME_EVICTED',
  ORTHOGRAPHIC_VIEWPORT_CREATED = 'ORTHOGRAPHIC_VIEWPORT_CREATED',

  // Enterprise MPR Workspace Events (Phase 6)
  MPR_WORKSPACE_CREATED = 'MPR_WORKSPACE_CREATED',
  VIEWPORT_LINKED = 'VIEWPORT_LINKED',
  CROSSHAIR_MOVED = 'CROSSHAIR_MOVED',
  REFERENCE_LINES_UPDATED = 'REFERENCE_LINES_UPDATED',
  SLICE_SYNCHRONIZED = 'SLICE_SYNCHRONIZED',
  CAMERA_SYNCHRONIZED = 'CAMERA_SYNCHRONIZED',
  VOI_SYNCHRONIZED = 'VOI_SYNCHRONIZED',
  MPR_LAYOUT_CHANGED = 'MPR_LAYOUT_CHANGED',

  // Enterprise 3D Volume Rendering Pipeline Events (Phase 7)
  VR_VIEWPORT_CREATED = 'VR_VIEWPORT_CREATED',
  TRANSFER_FUNCTION_CHANGED = 'TRANSFER_FUNCTION_CHANGED',
  RENDER_PRESET_CHANGED = 'RENDER_PRESET_CHANGED',
  CLIPPING_CHANGED = 'CLIPPING_CHANGED',
  QUALITY_CHANGED = 'QUALITY_CHANGED',
  VOLUME_RENDER_STARTED = 'VOLUME_RENDER_STARTED',
  VOLUME_RENDER_FINISHED = 'VOLUME_RENDER_FINISHED',

  // Enterprise Segmentation & Clinical Tooling Events (Phase 8)
  SEGMENTATION_CREATED = 'SEGMENTATION_CREATED',
  SEGMENTATION_UPDATED = 'SEGMENTATION_UPDATED',
  SEGMENTATION_DELETED = 'SEGMENTATION_DELETED',
  SEGMENTATION_VISIBILITY_CHANGED = 'SEGMENTATION_VISIBILITY_CHANGED',
  LABELMAP_UPDATED = 'LABELMAP_UPDATED',
  ANNOTATION_CREATED = 'ANNOTATION_CREATED',
  ANNOTATION_UPDATED = 'ANNOTATION_UPDATED',
  ANNOTATION_DELETED = 'ANNOTATION_DELETED',
  MEASUREMENT_CREATED = 'MEASUREMENT_CREATED',
  MEASUREMENT_UPDATED = 'MEASUREMENT_UPDATED',
  MEASUREMENT_DELETED = 'MEASUREMENT_DELETED',
  RTSTRUCT_IMPORTED = 'RTSTRUCT_IMPORTED',
  RTSTRUCT_EXPORTED = 'RTSTRUCT_EXPORTED',
  DICOM_SEG_IMPORTED = 'DICOM_SEG_IMPORTED',
  DICOM_SEG_EXPORTED = 'DICOM_SEG_EXPORTED',

  // Enterprise Registration, Fusion & Advanced Clinical Visualization Events (Phase 9)
  REGISTRATION_STARTED = 'REGISTRATION_STARTED',
  REGISTRATION_COMPLETED = 'REGISTRATION_COMPLETED',
  LANDMARK_UPDATED = 'LANDMARK_UPDATED',
  FUSION_CREATED = 'FUSION_CREATED',
  BLEND_MODE_CHANGED = 'BLEND_MODE_CHANGED',
  COLORMAP_CHANGED = 'COLORMAP_CHANGED',
  CPR_CREATED = 'CPR_CREATED',
  CENTERLINE_UPDATED = 'CENTERLINE_UPDATED',
  VESSEL_TRACKING_COMPLETED = 'VESSEL_TRACKING_COMPLETED',

  // Enterprise AI Platform Infrastructure Events (Before Phase 10)
  MODEL_REGISTERED = 'MODEL_REGISTERED',
  MODEL_LOADED = 'MODEL_LOADED',
  MODEL_UNLOADED = 'MODEL_UNLOADED',
  INFERENCE_STARTED = 'INFERENCE_STARTED',
  INFERENCE_PROGRESS = 'INFERENCE_PROGRESS',
  INFERENCE_COMPLETED = 'INFERENCE_COMPLETED',
  INFERENCE_FAILED = 'INFERENCE_FAILED',
  JOB_CANCELLED = 'JOB_CANCELLED',

  // Enterprise AI Applications, Structured Reporting & Workflow Automation Events (Phase 10)
  DETECTION_COMPLETED = 'DETECTION_COMPLETED',
  HEATMAP_GENERATED = 'HEATMAP_GENERATED',
  REPORT_GENERATED = 'REPORT_GENERATED',
  REPORT_EXPORTED = 'REPORT_EXPORTED',
  CRITICAL_FINDING_ALERT = 'CRITICAL_FINDING_ALERT',
  WORKFLOW_TASK_ASSIGNED = 'WORKFLOW_TASK_ASSIGNED',
  AUDIT_LOGGED = 'AUDIT_LOGGED',

  // Enterprise Performance & Scalability Infrastructure Events (Before Phase 11)
  FRAME_RENDERED = 'FRAME_RENDERED',
  FRAME_DROPPED = 'FRAME_DROPPED',
  STREAM_STARTED = 'STREAM_STARTED',
  STREAM_COMPLETED = 'STREAM_COMPLETED',
  CACHE_HIT = 'CACHE_HIT',
  CACHE_MISS = 'CACHE_MISS',
  GPU_MEMORY_WARNING = 'GPU_MEMORY_WARNING',
  BACKGROUND_TASK_STARTED = 'BACKGROUND_TASK_STARTED',
  BACKGROUND_TASK_FINISHED = 'BACKGROUND_TASK_FINISHED',
  PERFORMANCE_WARNING = 'PERFORMANCE_WARNING',

  // Enterprise Performance Optimization, Streaming & Enterprise Deployment Events (Phase 11)
  PROGRESSIVE_SLICE_LOADED = 'PROGRESSIVE_SLICE_LOADED',
  LOD_CHANGED = 'LOD_CHANGED',
  MONITOR_SYNCED = 'MONITOR_SYNCED',
  OFFLINE_STATUS_CHANGED = 'OFFLINE_STATUS_CHANGED',
  HEALTH_CHECK_PASSED = 'HEALTH_CHECK_PASSED',

  // Enterprise Validation, Security & Compliance Foundation Events (Before Phase 12)
  VALIDATION_STARTED = 'VALIDATION_STARTED',
  VALIDATION_COMPLETED = 'VALIDATION_COMPLETED',
  SECURITY_ALERT = 'SECURITY_ALERT',
  AUDIT_CREATED = 'AUDIT_CREATED',
  CONFIGURATION_CHANGED = 'CONFIGURATION_CHANGED',
  BACKUP_COMPLETED = 'BACKUP_COMPLETED',
  LICENSE_UPDATED = 'LICENSE_UPDATED',

  // Production Readiness, Clinical Validation & Enterprise Release Events (Phase 12)
  RELEASE_BUILD_STARTED = 'RELEASE_BUILD_STARTED',
  RELEASE_BUILD_COMPLETED = 'RELEASE_BUILD_COMPLETED',
  UPDATE_AVAILABLE = 'UPDATE_AVAILABLE',
  CRASH_REPORTED = 'CRASH_REPORTED',
  SUPPORT_BUNDLE_GENERATED = 'SUPPORT_BUNDLE_GENERATED',

  // Data & Cache Events
  IMAGE_LOADED = 'IMAGE_LOADED',
  CACHE_EVICTED = 'CACHE_EVICTED',

  // Interaction & Measurement Events
  TOOL_CHANGED = 'TOOL_CHANGED',
  WINDOW_LEVEL_CHANGED = 'WINDOW_LEVEL_CHANGED',
  CAMERA_MODIFIED = 'CAMERA_MODIFIED',

  // Error Event
  ENGINE_ERROR = 'ENGINE_ERROR',
}

export interface IEngineErrorPayload {
  module: string;
  message: string;
  error?: Error;
  timestamp: number;
}
