"""Initial schema

Revision ID: bdbfe1982068
Revises: None
Create Date: 2026-07-02 19:40:45.865504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbfe1982068'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('patient_birth_date', sa.String(), nullable=True),
    sa.Column('patient_sex', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('study_instance_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('recent_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('study_instance_uid', sa.String(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recent_studies_id'), 'recent_studies', ['id'], unique=False)
    op.create_table('studies',
    sa.Column('study_instance_uid', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('study_date', sa.String(), nullable=True),
    sa.Column('study_time', sa.String(), nullable=True),
    sa.Column('accession_number', sa.String(), nullable=True),
    sa.Column('study_description', sa.String(), nullable=True),
    sa.Column('modalities_in_study', sa.String(), nullable=True),
    sa.Column('number_of_study_related_series', sa.Integer(), nullable=True),
    sa.Column('number_of_study_related_instances', sa.Integer(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('study_instance_uid')
    )
    op.create_index(op.f('ix_studies_study_instance_uid'), 'studies', ['study_instance_uid'], unique=False)
    op.create_table('viewer_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('hotkeys', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viewer_preferences_id'), 'viewer_preferences', ['id'], unique=False)
    op.create_table('viewer_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active_study_uid', sa.String(), nullable=False),
    sa.Column('current_layout', sa.String(), nullable=True),
    sa.Column('active_viewport_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viewer_sessions_id'), 'viewer_sessions', ['id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('text_content', sa.String(), nullable=False),
    sa.Column('coords', sa.JSON(), nullable=False),
    sa.Column('study_instance_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['viewer_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_id'), 'annotations', ['id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('tool_type', sa.String(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('calculated_value', sa.Float(), nullable=True),
    sa.Column('mean_hu', sa.Float(), nullable=True),
    sa.Column('study_instance_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['viewer_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    op.create_table('series',
    sa.Column('series_instance_uid', sa.String(), nullable=False),
    sa.Column('study_instance_uid', sa.String(), nullable=True),
    sa.Column('series_number', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('series_description', sa.String(), nullable=True),
    sa.Column('number_of_series_related_instances', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_instance_uid'], ['studies.study_instance_uid'], ),
    sa.PrimaryKeyConstraint('series_instance_uid')
    )
    op.create_index(op.f('ix_series_series_instance_uid'), 'series', ['series_instance_uid'], unique=False)
    op.create_table('instances',
    sa.Column('sop_instance_uid', sa.String(), nullable=False),
    sa.Column('series_instance_uid', sa.String(), nullable=True),
    sa.Column('study_instance_uid', sa.String(), nullable=True),
    sa.Column('instance_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_instance_uid'], ['series.series_instance_uid'], ),
    sa.ForeignKeyConstraint(['study_instance_uid'], ['studies.study_instance_uid'], ),
    sa.PrimaryKeyConstraint('sop_instance_uid')
    )
    op.create_index(op.f('ix_instances_sop_instance_uid'), 'instances', ['sop_instance_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instances_sop_instance_uid'), table_name='instances')
    op.drop_table('instances')
    op.drop_index(op.f('ix_series_series_instance_uid'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_annotations_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_viewer_sessions_id'), table_name='viewer_sessions')
    op.drop_table('viewer_sessions')
    op.drop_index(op.f('ix_viewer_preferences_id'), table_name='viewer_preferences')
    op.drop_table('viewer_preferences')
    op.drop_index(op.f('ix_studies_study_instance_uid'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_recent_studies_id'), table_name='recent_studies')
    op.drop_table('recent_studies')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
